
'use client';

import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, variables?: Record<string, string>) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    dashboard: "Dashboard",
    tickets: "Tickets",
    tasks: "My tasks",
    analytics: "Analytics",
    settings: "Settings",
    requests: "Requests",
    newTicket: "New Ticket",
    signOut: "Sign Out",
    profile: "My Account",
    workspace: "WORKSPACE",
    organization: "ORGANIZATION",
    
    // Dashboard Stats
    openTickets: "Open tickets",
    pendingTickets: "Pending / Queue",
    slaBreaches: "SLA breaches",
    slaCompliance: "SLA compliance",
    avgResponse: "Avg response",
    resolved: "Resolved",
    closed: "Closed",
    reopened: "Reopened",
    inCampuses: "Assigned in campuses",
    totalLate: "Total late responses",
    standard: "Institution standard",
    firstReply: "First reply speed",
    selectedPeriod: "For selected period",
    liveView: "Live view of parent communications",
    personalQueue: "Personal queue for {{count}} campuses",
    divisionHealth: "Division health",
    open: "Open",
    breached: "Breached",
    
    // Charts
    slaTrend: "SLA compliance trend",
    slaTrendSub: "% of tickets responded to within SLA for the selected period",
    campusVolume: "Ticket Volume by Campus",
    campusVolumeSub: "Workload distribution across physical school locations.",
    divisionStatus: "Ticket Status by Division",
    divisionStatusSub: "Comparison between Active workload and Completed requests.",
    categoryStatus: "Ticket Status by Category",
    categoryStatusSub: "Workload distribution per administrative department.",
    channelMix: "Channel mix",
    channelMixSub: "Total volume across all entry points",
    total: "Total",
    ticketsByAssignee: "Tickets by Assignee",
    activeWorkload: "Active Workload",
    completedRequests: "Completed",

    // Analytics Page
    analyticsSub: "Performance insights for your assigned campuses.",
    noAnalyticsData: "No Data for your assigned campuses",
    noAnalyticsDataSub: "Insights will appear once tickets are processed for your campuses.",
    inboundVolumeTitle: "Inbound volume by channel — last 14 days",
    avgResolutionTimeTitle: "Average resolution time",
    byDivisionHours: "By division (hours)",
    topIssueCategoriesTitle: "Top issue categories",
    byVolumeTickets: "By volume of tickets",
    noResolvedTickets: "No resolved tickets yet for the selected period.",
    noIssuesRecorded: "No issues recorded for the current filter criteria.",

    // Requests Page
    actionRequests: "Action Requests",
    requestsSub: "Manage ticket transfers and staff reassignment requests.",
    activeRequestsLabel: "Active Requests",
    transferRequestedTitle: "Transfer Requested",
    reassignRequestedTitle: "Reassignment Requested",
    approveBtn: "Approve",
    rejectBtn: "Reject",
    recentlyProcessed: "Recently Processed",
    processedBy: "Processed by",
    noActiveRequests: "No active requests",
    everythingProcessed: "Everything is processed for now.",
    selectNewAssignee: "Select New Assignee",
    chooseAvailableEmployee: "Choose an available employee from the category.",
    availableStaff: "Available Staff",
    confirmApproval: "Confirm Approval",
    cancel: "Cancel",
    reassignment: "Reassignment",
    transfer: "Transfer",
    transferReqMsg: "{{name}} requested to move Ticket #{{id}} to {{dept}}",
    reassignReqMsg: "{{name}} requested to reassign Ticket #{{id}}",

    // Tickets Page
    ticketsPageTitle: "Tickets",
    ticketsPageSub: "View and manage institutional tickets.",
    searchPlaceholder: "Search ID, subject, staff...",
    allCategories: "All Categories",
    allChannels: "All Channels",
    allSLA: "All SLA",
    slaBreached: "SLA Breached",
    slaAtRisk: "At risk (<2h)",
    export: "Export",
    columns: "Columns",
    toggleVisibility: "Toggle visibility",
    clearFilters: "Clear Filters",
    
    // Table Headers
    idCol: "ID",
    detailsCol: "Details",
    dateCreatedCol: "Date Created",
    timeCreatedCol: "Time Created",
    dateFirstRespCol: "Date First Resp",
    timeFirstRespCol: "Time First Resp",
    assignedTechCol: "Assigned Tech",
    priorityCol: "Priority",
    statusCol: "Status",
    channelCol: "Channel",
    divisionCol: "Division",
    campusCol: "Campus",
    slaStatusCol: "SLA",
    tagsCol: "Tags",
    dateUpdatedCol: "Date Updated",
    timeUpdatedCol: "Time Updated",
    dateResolvedCol: "Date Resolved",
    timeResolvedCol: "Time Resolved",
    dateClosedCol: "Date Closed",
    timeClosedCol: "Time Closed",

    // New Ticket Page
    createTicketTitle: "Create New Ticket",
    createTicketSub: "Staff Portal: Register a parent request or call.",
    creatingAs: "Creating as: {{name}}",
    identityLinkNote: "Your staff identity will be linked to this record.",
    channelLabel: "Channel",
    parentStudentInfo: "Parent & Student Information",
    parentNameLabel: "Parent Name",
    parentEmailLabel: "Parent Email",
    studentBlbIdLabel: "Student BLB ID",
    assignmentDetails: "Assignment & Details",
    campusLabel: "Campus",
    schoolLabel: "School",
    divisionLabel: "Division",
    categoryLabel: "Category",
    gradeLabel: "Grade",
    notesLabel: "Notes / Request Body",
    notesPlaceholder: "Describe the issue or request in detail...",
    titleLabel: "Ticket Title",
    titlePlaceholder: "Enter a brief title (max 100 characters)",
    attachmentsLabel: "Attachments (PDF or PNG/JPG)",
    clickToUpload: "Click or drag to upload",
    fileTypesNote: "PDF, PNG, JPG ONLY",
    uploadWaitNote: "Please wait, large files take a few seconds to upload...",
    submitting: "Uploading & Submitting...",
    submitTicket: "Submit Ticket",
    invalidFileType: "Invalid file type",
    invalidFileDetail: "File \"{{name}}\" is not a PDF or Image.",
    optional: "optional",
    fullNamePlaceholder: "Full Name",
    emailPlaceholder: "email@example.com",
    blbPlaceholder: "e.g. 12345",
    selectCampus: "Select campus",
    selectSchool: "Select school",
    selectDivision: "Select division",
    selectCategory: "Select category",
    selectGrade: "Select grade",
    minCharsError: "The notes must be at least 10 characters long.",

    // Ticket Detail Page
    actions: "Actions",
    details: "Details",
    resolve: "Resolve",
    close: "Close",
    reopen: "Reopen",
    waiting: "Waiting",
    duplicate: "Duplicate",
    transferCategory: "Transfer category",
    requestTransfer: "Request transfer",
    assignPerson: "Assign to person",
    requestReassignment: "Request reassignment",
    ticketId: "Ticket ID",
    division: "Division",
    school: "School",
    campus: "Campus",
    category: "Category",
    priority: "Priority",
    tags: "Tags",
    replyVia: "Reply via {{channel}}",
    internalNote: "Internal note",
    internalTeamOnly: "Internal team only",
    writeResponse: "Write your response...",
    saveInternalNote: "Save internal note",
    reply: "Reply",
    activityLog: "Activity log",
    requesterDetails: "Requester details",
    conversationLocked: "Conversation Locked",
    lockedSub: "This ticket is marked as {{status}}. Please reopen the ticket if you need to send further replies.",
    initialRequestCreatedBy: "Initial request created by {{name}}",
    startFollowUp: "Start follow-up",
    selectTag: "Select tag",
    grade: "Grade",
    noEmail: "No Email",
    attachedFiles: "Attached Files ({{count}})",
    viewFullSize: "View Full Size",
    deleteMessage: "Delete Message",
    confirmDeleteMessage: "Are you sure you want to delete this message?",
    deleteTicket: "Delete Ticket",
    deleteTicketConfirmTitle: "Delete Ticket",
    deleteTicketConfirmDesc: "Are you sure you want to permanently delete this ticket? All messages, internal notes, and attachments associated with this ticket will be removed. This action cannot be undone.",
    deletingTicket: "Deleting Ticket...",
    guestVerificationTitle: "Ticket Access Verification",
    enterParentEmail: "Please enter the parent email address associated with this ticket to view the details.",
    verifyBtn: "Verify & View Ticket",
    invalidGuestEmail: "The email address provided does not match our records for this ticket.",
    assignedTo: "Assigned To",

    // Profile Page
    newPassword: "New Password",
    passwordPlaceholder: "Leave blank to keep current password",
    passwordUpdated: "Password updated successfully",
    profileUpdated: "Profile Updated",
    profileUpdatedSub: "Your information has been successfully updated.",
    assignedCampuses: "Assigned Campuses",
    campusContactAdminNote: "* Assigned campuses can only be managed by a system administrator.",

    // Statuses & States
    unassigned: "Unassigned",
    notYet: "not yet",
    na: "N/A",
    breachedAgo: "Breached {{hours}}h ago",
    dueIn: "Due in {{hours}}h",
    compliant: "Compliant",
    noTags: "No tags",
    urgent: "Urgent",
    high: "High",
    normal: "Normal",
    low: "Low",
    showing: "Showing",
    to: "to",
    of: "of",
    statusUpdated: "Status Updated",
    statusSetTo: "Ticket status set to {{status}}.",
    awaitingAssignment: "Awaiting Assignment",

    // Tasks Page
    slaBreachedOnly: "SLA BREACHED ONLY",
    allStatus: "All Status",
    noTasks: "No tickets assigned in your campuses.",
    campusesCountLabel: "{{count}} Campuses",

    // General
    search: "Search...",
    loading: "Loading NIS CRM...",
    available: "Available",
    busy: "Busy",
    status: "Status",
    queue: "Queue",
    autoAssignQueue: "Auto-Assign Queue",
    autoAssignQueueDesc: "Distribute queued tickets to available logged-in agents using round-robin",
    assigningQueue: "Assigning queued tickets...",
    queueAssignedSuccess: "Successfully assigned {{count}} queued tickets via round-robin",
    noQueuedTickets: "No queued tickets in queue",
    noAgentsAvailable: "No available logged-in agents available for the queued tickets",
    inProgress: "In Progress",
    closed: "Closed",
    waiting: "Waiting",
    reviewNow: "Review now",
    anyDate: "Any Date",
    notifications: "Notifications",
    unread: "Unread",
    allCaughtUp: "All caught up!",
    noNotifications: "You don't have any notifications right now.",
    viewAll: "View all notifications",
    justNow: "Just now",
    studentBlbId: "Student BLB ID",
    
    // Settings
    adminSettings: "Settings & Administration",
    manageOrg: "Manage your organization structure, system preferences, and staff members.",
    branchesSettings: "Branches settings",
    employeeMgmt: "Employees management",
    workingHours: "Working Hours",
    tagsSettings: "Tags settings",
    slaPolicies: "SLA Policies",
    afterHoursEmail: "After-Hours Ticket Email",
    systemLog: "System Log",
    actionLog: "Action Log",
    actionLogDesc: "Complete real-time audit trail of every action, update, and configuration change across the system.",
    searchLogs: "Search events, actors, ticket #, message...",
    allEvents: "All Events",
    ticketEvents: "Tickets",
    userEvents: "Staff & Users",
    orgEvents: "Organization",
    slaEvents: "SLA & Automation",
    dateFilter: "Date",
    allTime: "All Time",
    today: "Today",
    past7Days: "Past 7 Days",
    past30Days: "Past 30 Days",
    exportLogs: "Export CSV",
    noLogsFound: "No action logs found.",
    eventDetails: "Event Details",
    actor: "Actor",
    totalActions: "Total Actions",
    actionsToday: "Actions Today",
    adminOnlyBadge: "Admin Only",
    categories: "Categories",
    divisions: "Divisions",
    schools: "Schools",
    campuses: "Campuses",
    grades: "Grades & Year Groups",
    staffMembers: "Staff Members",
    slaResponsePolicies: "SLA response policies",
    slaDescription: "Maximum hours allowed for first staff response, by channel and priority. The SLA clock starts when a ticket is created.",
    savePolicies: "Save Policies",
    channel: "Channel",
    slaNote: "Values in hours. Lower is stricter. Changes apply to all calculations; existing tickets keep their original creation timestamp.",
    editCategory: "Edit Category",
    addNewCategory: "Add New Category",
    addCategory: "Add Category",
    saveChanges: "Save Changes",
    afterHoursDescription: "Customize the automated response for specific departments or the entire organization.",
    availableVariables: "Available Variables",
    emailSubject: "Email Subject",
    messageBody: "Message Body",
    saveTemplate: "Save Template",
    preview: "Preview",
    edit: "Edit",
    categoriesSub: "Administrative units for ticket routing.",
    divisionsSub: "Educational curriculum frameworks.",
    schoolsSub: "Define and manage educational entities.",
    campusesSub: "Manage physical school locations.",
    gradesSub: "Manage academic levels across all divisions.",
    
    // Settings Table & List Keys
    systemEmployees: "System Employees",
    myCategoryStaff: "My Category Staff",
    searchEmployees: "Search employees...",
    addEmployee: "Add Employee",
    employee: "Employee",
    role: "Role",
    accountStatus: "Account Status",
    verified: "Verified",
    noAccess: "No Access",
    createLogin: "Create Login",
    delete: "Delete",
    noEmployeesFound: "No employees found matching your criteria.",
    actions: "Actions",
    noCategories: "No categories configured yet.",
    addDivision: "Add Division",
    divisionName: "Division Name",
    noDivisions: "No divisions configured.",
    addSchool: "Add School",
    schoolName: "School Name",
    noSchools: "No schools added yet.",
    selectSchool: "Select Schools",
    addCampus: "Add Campus",
    campusName: "Campus Name",
    noCampuses: "No campuses found.",
    addGrade: "Add Grade",
    gradeName: "Grade Name",
    noGrades: "No grades found.",
    selectGrade: "Select Grades",
    addPredefinedTag: "Add Predefined Tag",
    tagName: "Tag Name",
    noTagsFound: "No predefined tags found.",
    workingHoursByCategory: "Working hours by category",
    selectCategoryToConfigure: "Select Category to Configure",
    day: "Day",
    startTime: "Start Time",
    endTime: "End Time",
    saveHours: "Save Hours",
    afterHoursEmailTitle: "After-Hours Ticket Email",
    selectCategoryToEdit: "Select Target Category to Edit",
    entireOrg: "Entire Organization (Global Default)",
    AvailableVariables: "Available Variables",
    availableStaff: "Available Staff",
    loadingStaff: "Loading staff...",
    selectEmployee: "Select Employee",
    noAvailableStaffFound: "No available staff found.",
    confirmApproval: "Confirm Approval",
    reassignment: "Reassignment",
    transfer: "Transfer",
    from: "From",
    to: "To",
    activeRequestsLabel: "Active Requests",
    recentlyProcessed: "Recently Processed",
    processedBy: "Processed by",
    noActiveRequests: "No active requests",
    everythingProcessed: "Everything is processed for now.",
    approveBtn: "Approve",
    rejectBtn: "Reject",
    anyDate: "Any Date",
    searchPlaceholder: "Search ID, subject, staff...",
    tagsDescription: "Create and manage tags that staff can assign to tickets for better classification and reporting.",
    tag: "Tag",
    Phone: "Phone",
    "Walk-in": "Walk-in",
    "Social Media": "Social Media",
    "General / Global": "General / Global",
    Email: "Email",
    Web: "Web",
    Other: "Other",
    Form: "Form",
    Sunday: "Sunday",
    Monday: "Monday",
    Tuesday: "Tuesday",
    Wednesday: "Wednesday",
    Thursday: "Thursday",
    Friday: "Friday",
    Saturday: "Saturday",
    closed: "Closed",
  },
  ar: {
    // Nav
    dashboard: "لوحة التحكم",
    tickets: "التذاكر",
    tasks: "مهامي اليومية",
    analytics: "التحليلات",
    settings: "الإعدادات والضبط",
    requests: "الطلبات الواردة",
    newTicket: "تذكرة جديدة",
    signOut: "تسجيل الخروج",
    profile: "حسابي الشخصي",
    workspace: "مساحة العمل",
    organization: "إدارة المؤسسة",
    
    // Dashboard Stats
    openTickets: "تذاكر مفتوحة",
    pendingTickets: "في الانتظار / القائمة",
    slaBreaches: "تجاوزات SLA",
    slaCompliance: "نسبة الالتزام",
    avgResponse: "متوسط الرد",
    resolved: "تم حلها",
    closed: "مغلقة",
    reopened: "أعيد فتحها",
    inCampuses: "في الفروع التابعة لك",
    totalLate: "إجمالي الردود المتأخرة",
    standard: "المعيار العام للمدرسة",
    firstReply: "سرعة الرد الأول",
    selectedPeriod: "للفترة المختارة",
    liveView: "بث مباشر لتواصل أولياء الأمور",
    personalQueue: "قائمة الانتظار لـ {{count}} فروع",
    divisionHealth: "صحة الأداء حسب القطاعات",
    open: "مفتوح",
    breached: "متجاوز",

    // Charts
    slaTrend: "اتجاه الالتزام بـ SLA",
    slaTrendSub: "% التذاكر التي تم الرد عليها ضمن الوقت المحدد للفترة المختارة",
    campusVolume: "حجم التذاكر حسب الفرع",
    campusVolumeSub: "توزيع ضغط العمل عبر المواقع الجغرافية للمدارس.",
    divisionStatus: "حالة التذاكر حسب القطاع",
    divisionStatusSub: "مقارنة بين ضغط العمل النشط والطلبات المكتملة.",
    categoryStatus: "حالة التذاكر حسب القسم",
    categoryStatusSub: "توزيع عبء العمل عبر الوحدات الإدارية.",
    channelMix: "توزيع قنوات الاتصال",
    channelMixSub: "إجمالي حجم العمل عبر جميع نقاط الدخول",
    total: "الإجمالي",
    ticketsByAssignee: "التذاكر حسب الموظف",
    activeWorkload: "ضغط العمل النشط",
    completedRequests: "طلبات مكتملة",

    // Analytics Page
    analyticsSub: "رؤى الأداء للفروع التابعة لك.",
    noAnalyticsData: "لا توجد بيانات للفروع التابعة لك",
    noAnalyticsDataSub: "ستظهر التحليلات بمجرد معالجة التذاكر في فروعك.",
    inboundVolumeTitle: "حجم التذاكر الواردة حسب القناة - آخر ١٤ يوماً",
    avgResolutionTimeTitle: "متوسط وقت الحل",
    byDivisionHours: "حسب القطاع (بالساعات)",
    topIssueCategoriesTitle: "أعلى فئات المشكلات",
    byVolumeTickets: "By volume of tickets",
    noResolvedTickets: "لا توجد تذاكر تم حلها لهذه الفترة.",
    noIssuesRecorded: "لا توجد سجلات مشكلات مطابقة للمعايير.",

    // Requests Page
    actionRequests: "طلب الإجراءات",
    requestsSub: "إدارة طلبات نقل التذاكر وإعادة تعيين الموظفين.",
    activeRequestsLabel: "طلبات نشطة",
    transferRequestedTitle: "طلب نقل تذكرة",
    reassignRequestedTitle: "طلب إعادة تعيين موظف",
    approveBtn: "موافقة",
    rejectBtn: "رفض",
    recentlyProcessed: "طلبات عولجت مؤقراً",
    processedBy: "عولج بواسطة",
    noActiveRequests: "لا توجد طلبات نشطة",
    everythingProcessed: "تمت معالجة كل شيء حالياً.",
    selectNewAssignee: "اختر موظفاً جديداً",
    chooseAvailableEmployee: "اختر موظفاً متاحاً من هذا القسم لإسناد التذكرة إليه.",
    availableStaff: "الموظفين المتاحين",
    confirmApproval: "تأكيد المواقة",
    cancel: "إلغاء",
    reassignment: "إعادة تعيين",
    transfer: "نقل",
    transferReqMsg: "طلب {{name}} نقل التذكرة رقم {{id}} إلى قسم {{dept}}",
    reassignReqMsg: "طلب {{name}} إعادة تعيين التذكرة رقم {{id}}",

    // New Ticket Page
    createTicketTitle: "إنشاء تذكرة جديدة",
    createTicketSub: "بوابة الموظفين: تسجيل طلب أو مكالمة من ولي أمر.",
    creatingAs: "إنشاء بواسطة: {{name}}",
    identityLinkNote: "سيتم ربط هويتك الوظيفية بهذا السجل.",
    channelLabel: "قناة الاتصال",
    parentStudentInfo: "بيانات ولي الأمر والطالب",
    parentNameLabel: "اسم ولي الأمر",
    parentEmailLabel: "البريد الإلكتروني لولي الأمر",
    studentBlbIdLabel: "رقم الطالب BLB",
    assignmentDetails: "التوجيه والتفاصيل",
    campusLabel: "الفرع",
    schoolLabel: "المدرسة",
    divisionLabel: "القطاع",
    categoryLabel: "القسم",
    gradeLabel: "الصف",
    notesLabel: "الملاحظات / نص الطلب",
    notesPlaceholder: "صف المشكلة أو الطلب بالتفصيل...",
    titleLabel: "عنوان التذكرة",
    titlePlaceholder: "أدخل عنواناً موجزاً (بحد أقصى 100 حرف)",
    attachmentsLabel: "المرفقات (PDF أو PNG/JPG)",
    clickToUpload: "انقر أو اسحب للتحميل",
    fileTypesNote: "ملفات PDF, PNG, JPG فقط",
    uploadWaitNote: "يرجى الانتظار، الملفات الكبيرة تستغرق بضع ثوانٍ للرفع...",
    submitting: "جاري الرفع والإرسال...",
    submitTicket: "إرسال التذكرة",
    invalidFileType: "نوع ملف غير صالح",
    invalidFileDetail: "الملف \"{{name}}\" ليس ملف PDF أو صورة.",
    optional: "اختياري",
    fullNamePlaceholder: "الاسم الكامل",
    emailPlaceholder: "البريد الإلكتروني",
    blbPlaceholder: "مثال: 12345",
    selectCampus: "اختر الفرع",
    selectSchool: "اختر المدرسة",
    selectDivision: "اختر القطاع",
    selectCategory: "اختر القسم",
    selectGrade: "اختر الصف",
    minCharsError: "يجب أن لا يقل نص الطلب عن 10 حروف.",

    // Ticket Detail Page
    actions: "الإجراءات",
    details: "التفاصيل",
    resolve: "تم الحل",
    close: "إغلاق",
    reopen: "إعادة فتح",
    waiting: "في انتظار الرد",
    duplicate: "مكررة",
    transferCategory: "نقل القسم",
    requestTransfer: "طلب نقل",
    assignPerson: "تعيين موظف",
    requestReassignment: "طلب إعادة تعيين",
    ticketId: "رقم التذكرة",
    division: "القطاع",
    school: "المدرسة",
    campus: "الفرع",
    category: "القسم",
    priority: "الأولوية",
    tags: "التاقات",
    replyVia: "الرد عبر {{channel}}",
    internalNote: "ملاحظة داخلية",
    internalTeamOnly: "القسم الداخلي فقط",
    writeResponse: "اكتب ردك هنا...",
    saveInternalNote: "حفظ الملاحظة",
    reply: "إرسال الرد",
    activityLog: "سجل النشاط",
    requesterDetails: "بيانات صاحب الطلب",
    conversationLocked: "المحادثة مغلقة",
    lockedSub: "هذه التذكرة مغلقة حالياً كـ {{status}}. يرجى إعادة فتحها لإضافة ردود جديدة.",
    initialRequestCreatedBy: "تم إنشاء الطلب بواسطة {{name}}",
    startFollowUp: "بدء متابعة",
    selectTag: "اختر تاق",
    grade: "الصف الدراسي",
    noEmail: "No Email",
    attachedFiles: "الملفات المرفقة ({{count}})",
    viewFullSize: "عرض الحجم الكامل",
    deleteMessage: "حذف الرسالة",
    confirmDeleteMessage: "هل أنت متأكد من حذف هذه الرسالة؟",
    deleteTicket: "حذف التذكرة",
    deleteTicketConfirmTitle: "حذف التذكرة",
    deleteTicketConfirmDesc: "هل أنت متأكد من رغبتك في حذف هذه التذكرة نهائياً؟ سيتم مسح جميع الرسائل والملاحظات والمرفقات المرتبطة بها، ولا يمكن التراجع عن هذا الإجراء.",
    deletingTicket: "جاري حذف التذكرة...",
    guestVerificationTitle: "تحقق من الوصول للتذكرة",
    enterParentEmail: "يرجى إدخال البريد الإلكتروني لولي الأمر المرتبط بهذه التذكرة لعرض التفاصيل.",
    verifyBtn: "تحقق وافتح التذكرة",
    invalidGuestEmail: "البريد الإلكتروني المدخل لا يطابق السجلات لهذه التذكرة.",
    assignedTo: "الموظف المسؤول",

    // Profile Page
    newPassword: "كلمة مرور جديدة",
    passwordPlaceholder: "اتركه فارغاً للاحتفاظ بكلمة المرور الحالية",
    passwordUpdated: "تم تحديث كلمة المرور بنجاح",
    profileUpdated: "تم تحديث الملف الشخصي",
    profileUpdatedSub: "تم تحديث بياناتك بنجاح.",
    assignedCampuses: "الفروع الموكلة إليك",
    campusContactAdminNote: "* الفروع الموكلة إليك يتم إدارتها من قبل مدير النظام فقط.",

    // Tickets Page
    ticketsPageTitle: "التذاكر",
    ticketsPageSub: "عرض وإدارة تذاكر الدعم الفني والتواصل.",
    searchPlaceholder: "بحث برقم التذكرة، الموضوع، الموظف...",
    allCategories: "جميع الأقسام",
    allChannels: "جميع القنوات",
    allSLA: "جميع الالتزامات",
    slaBreached: "تجاوز الـ SLA",
    slaAtRisk: "في خطر (< ساعتين)",
    export: "تصدير",
    columns: "الأعمدة",
    toggleVisibility: "إظهار/إخفاء",
    clearFilters: "إعادة ضبط الفلاتر",

    // Table Headers
    idCol: "المعرف",
    detailsCol: "التفاصيل",
    dateCreatedCol: "تاريخ الإنشاء",
    timeCreatedCol: "وقت الإنشاء",
    dateFirstRespCol: "تاريخ أول رد",
    timeFirstRespCol: "وقت أول رد",
    assignedTechCol: "الموظف المسؤول",
    priorityCol: "الأولوية",
    statusCol: "الحالة",
    channelCol: "القناة",
    divisionCol: "القطاع",
    campusCol: "الفرع",
    slaStatusCol: "الالتزام (SLA)",
    tagsCol: "التاقات",
    dateUpdatedCol: "تاريخ التحديث",
    timeUpdatedCol: "وقت التحديث",
    dateResolvedCol: "تاريخ الحل",
    timeResolvedCol: "وقت الحل",
    dateClosedCol: "تاريخ الإغلاق",
    timeClosedCol: "وقت الإغلاق",

    // Statuses & States
    unassigned: "غير معين",
    notYet: "ليس بعد",
    na: "غير متاح",
    breachedAgo: "تأخر بـ {{hours}} ساعة",
    dueIn: "متبقي {{hours}} ساعة",
    compliant: "ملتزم",
    noTags: "بدون تاقات",
    urgent: "عاجل جداً",
    high: "مرتفع",
    normal: "عادي",
    low: "منخفض",
    showing: "عرض",
    to: "to",
    of: "of",
    statusUpdated: "تم تحديث الحالة",
    statusSetTo: "تم تغيير حالة التذكرة إلى {{status}}.",
    awaitingAssignment: "في انتظار التعيين",

    // Tasks Page
    slaBreachedOnly: "التذاكر المتجاوزة فقط",
    allStatus: "جميع الحالات",
    noTasks: "لا توجد تذاكر معينة في الفروع التابعة لك حالياً.",
    campusesCountLabel: "{{count}} فروع",

    // General
    search: "بحث عن التذاكر...",
    loading: "جاري تحميل نظام NIS CRM...",
    available: "متاح الآن",
    busy: "مشغول",
    status: "الحالة",
    queue: "في الانتظار",
    autoAssignQueue: "توزيع قائمة الانتظار تلقائياً",
    autoAssignQueueDesc: "توزيع تذاكر قائمة الانتظار على الموظفين المتاحين والمتصلين بالتساوي (Round-Robin)",
    assigningQueue: "جاري توزيع تذاكر قائمة الانتظار...",
    queueAssignedSuccess: "تم توزيع {{count}} تذكرة بنجاح بنظام التناوب",
    noQueuedTickets: "لا توجد تذاكر في قائمة الانتظار",
    noAgentsAvailable: "لا يوجد موظفون متاحون ومتصلون حالياً لتغطية تذاكر الانتظار",
    inProgress: "قيد التنفيذ",
    closed: "مغلقة نهائياً",
    waiting: "في انتظار الرد",
    duplicate: "مكررة",
    reviewNow: "راجع الآن",
    anyDate: "أي تاريخ",
    notifications: "التنبيهات",
    unread: "غير مقروء",
    allCaughtUp: "أنت مواكب لكل شيء!",
    noNotifications: "ليس لديك أي إشعارات حالياً.",
    viewAll: "عرض كل التنبيهات",
    justNow: "الآن",
    studentBlbId: "رقم الطالب (BLB ID)",

    // Settings
    adminSettings: "Settings & Administration",
    manageOrg: "إدارة الهيكل التنظيمي، تفضيلات النظام، وبيانات الموظفين.",
    branchesSettings: "إعدادات الفروع",
    employeeMgmt: "إدارة الموظفين",
    workingHours: "ساعات العمل",
    tagsSettings: "إعدادات التاقات",
    slaPolicies: "سياسات الـ SLA",
    afterHoursEmail: "ايميل خارج ساعات العمل",
    systemLog: "سجل النظام (System Log)",
    actionLog: "سجل العمليات (Action Log)",
    actionLogDesc: "سجل تدقيق مباشر وشامل لجميع العمليات، التعديلات، وتغييرات التكوين في النظام.",
    searchLogs: "بحث في العمليات، المنفذ، رقم التذكرة، الرسائل...",
    allEvents: "جميع العمليات",
    ticketEvents: "التذاكر",
    userEvents: "الموظفون والمستخدمون",
    orgEvents: "المؤسسة والفروع",
    slaEvents: "الـ SLA والتشغيل الآلي",
    dateFilter: "التاريخ",
    allTime: "كل الأوقات",
    today: "اليوم",
    past7Days: "آخر 7 أيام",
    past30Days: "آخر 30 يوماً",
    exportLogs: "تصدير CSV",
    noLogsFound: "لا توجد عمليات مسجلة تطابق البحث.",
    eventDetails: "تفاصيل العملية",
    actor: "المنفذ",
    totalActions: "إجمالي العمليات",
    actionsToday: "عمليات اليوم",
    adminOnlyBadge: "للأدمن فقط",
    categories: "الأقسام (Categories)",
    divisions: "القطاعات (Divisions)",
    schools: "المدارس",
    campuses: "الفروع (Campuses)",
    grades: "الصفوف والمراحل الدراية",
    staffMembers: "طاقم العمل",
    slaResponsePolicies: "سياسات استجابة الـ SLA",
    slaDescription: "أقصى عدد ساعات مسموح به للرد الأول للموظف، حسب القناة والأولوية. يبدأ عداد الـ SLA عند إنشاء التذكرة.",
    savePolicies: "حفظ السياسات",
    channel: "القناة",
    slaNote: "القيم بالساعات. القيمة الأقل تعني صرامة أكبر. التغييرات تطبق على جميع الحسابات؛ التذاكر القديفة تحتفظ بوقت إنشائها الأصلي.",
    editCategory: "تعديل القسم",
    addNewCategory: "إضافة قسم جديد",
    addCategory: "إضافة قسم",
    saveChanges: "حفظ التغييرات",
    afterHoursDescription: "تخصيص الرد الآلي لأقسام معينة أو للمؤسسة بالكامل.",
    availableVariables: "المتغيرات المتاحة",
    emailSubject: "موضوع الإيميل",
    messageBody: "نص الرسالة",
    saveTemplate: "حفظ القالب",
    preview: "معاينة",
    edit: "تعديل",
    categoriesSub: "Administrative units for ticket routing.",
    divisionsSub: "Educational curriculum frameworks.",
    schoolsSub: "Define and manage educational entities.",
    campusesSub: "Manage physical school locations.",
    gradesSub: "Manage academic levels across all divisions.",

    // Settings Table & List Keys
    systemEmployees: "System Employees",
    myCategoryStaff: "My Category Staff",
    searchEmployees: "Search employees...",
    addEmployee: "إضافة موظف",
    employee: "Employee",
    role: "Role",
    accountStatus: "Account Status",
    verified: "Verified",
    noAccess: "No Access",
    createLogin: "Create Login",
    delete: "Delete",
    noEmployeesFound: "No employees found matching your criteria.",
    actions: "الإجراءات",
    noCategories: "No categories configured yet.",
    addDivision: "Add Division",
    divisionName: "Division Name",
    noDivisions: "No divisions configured.",
    addSchool: "Add School",
    schoolName: "School Name",
    noSchools: "No schools added yet.",
    selectSchool: "اختر المدارس",
    addCampus: "Add Campus",
    campusName: "Campus Name",
    noCampuses: "No campuses found.",
    addGrade: "Add Grade",
    gradeName: "Grade Name",
    noGrades: "No grades found.",
    selectGrade: "اختر المراحل / الصفوف",
    addPredefinedTag: "Add Predefined Tag",
    tagName: "Tag Name",
    noTagsFound: "No predefined tags found.",
    workingHoursByCategory: "Working hours by category",
    selectCategoryToConfigure: "Select Category to Configure",
    day: "Day",
    startTime: "Start Time",
    endTime: "End Time",
    saveHours: "Save Hours",
    afterHoursEmailTitle: "After-Hours Ticket Email",
    selectCategoryToEdit: "Select Target Category to Edit",
    entireOrg: "Entire Organization (Global Default)",
    AvailableVariables: "Available Variables",
    availableStaff: "Available Staff",
    loadingStaff: "Loading staff...",
    selectEmployee: "Select Employee",
    noAvailableStaffFound: "No available staff found.",
    confirmApproval: "تأكيد الموافقة",
    reassignment: "إعادة تعيين",
    transfer: "نقل",
    from: "من",
    to: "إلى",
    activeRequestsLabel: "طلبات نشطة",
    recentlyProcessed: "طلبات عولجت مؤقراً",
    processedBy: "عولج بواسطة",
    noActiveRequests: "No active requests",
    everythingProcessed: "Everything is processed for now.",
    approveBtn: "موافقة",
    rejectBtn: "رفض",
    anyDate: "أي تاريخ",
    searchPlaceholder: "Search ID, subject, staff...",
    tagsDescription: "Create and manage tags that staff can assign to tickets for better classification and reporting.",
    tag: "Tag",
    Phone: "هاتف",
    "Walk-in": "زيارة",
    "Social Media": "تواصل اجتماعي",
    "General / Global": "عام / عالمي",
    Email: "إيميل",
    Web: "ويب",
    Other: "أخرى",
    Form: "نموذج",
    Sunday: "الأحد",
    Monday: "الاثنين",
    Tuesday: "الثلاثاء",
    Wednesday: "الأربعاء",
    Thursday: "الخميس",
    Friday: "الجمعة",
    Saturday: "السبت",
    closed: "مغلق",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('nis-lang') as Language;
    if (saved && (saved === 'en' || saved === 'ar')) {
      setLanguage(saved);
      document.documentElement.dir = saved === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.lang = saved;
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('nis-lang', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  const t = (key: string, variables?: Record<string, string>) => {
    let translation = translations[language][key] || key;
    if (variables) {
      Object.entries(variables).forEach(([k, v]) => {
        translation = translation.replace(`{{${k}}}`, v);
      });
    }
    return translation;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
